name: nuitka

on:
  push:
    branches:
    - main
    - dev

jobs:
  build-nuitka:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
           python-version: 3.13
      - run: |
          pip install nuitka jc
      - run: |
          cd /opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages
          python -m nuitka --standalone --include-package=jc --onefile jc
    
